hashes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from quipohash.language import set_language

app_name = 'hashes'

from hashes.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('create-payment-intent/<pk>/', StripeIntentView.as_view(), name='create-payment-intent'),
    #path('', ProductLandingPageView.as_view(), name='landing-page'),
    path('create-checkout-session/<pk>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session')
]

quipohash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from quipohash.language import set_language

from quipohash import urls

from hashes.views import upload, generate_hash, query, query_result, SuccessView, stripe_webhook, CancelView, visualizar
from hashes.view_e_certificate import e_certificate


urlpatterns = [
    # # path('', ),
    path('admin/', admin.site.urls),
    path('hashes/', include('hashes.urls')),

    path('success/', SuccessView.as_view(), name='success'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),


    path('hash/', generate_hash, name='hash'),
    path('query_result/', query_result, name='query_result'),
    path('query_result/<str:hash_code>/', query_result, name='query_result_with_code'),
    path('e-certificate/<int:hash_pk>/', e_certificate, name='e_certificate'),
    path('admin/', admin.site.urls),
    path('', query, name='query'),
    path('upload/', upload, name='upload'),
    path('visualizar/<str:hash>/', visualizar, name='visualizar'),
]

urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
    path("set_language/<str:language>", set_language, name="set-language"),
    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # Adicionar Isto

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hashes/models.py
from django.db import models
from django.contrib.auth.models import User


class Hash(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)  # will be 'quipo' if no one is logged.
    hash = models.CharField(db_index=True, max_length=64)  # the generated hash
    description = models.CharField(max_length=250)  # a description to facilitate remembering which file is it about.
    price = models.IntegerField(default=0)  # cents
    bchain_link = models.URLField(max_length=250, null=True, blank=True)  # URL pointing to the transaction in the explorer.
    payment_at = models.DateTimeField(null=True, blank=True)  # date/time of payment when it is concluded.
    transaction_at = models.DateTimeField(null=True, blank=True)  # date/time when the transaction was concluded (recorded on the bchain).
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    transaction_hash = models.CharField(max_length=500, null=True, blank=True)
    Picture = models.ImageField(upload_to='media/', null=True, blank=True)  # the generated hash
    Picture_noise = models.ImageField(upload_to='media/', null=True, blank=True)  # the generated hash
    expired = models.BooleanField(null=True, blank=True)

    class Meta:

        constraints = [
            models.UniqueConstraint(fields=['hash'], name='unique_hash')  # ensures that a file is not registered twice
        ]

    def __str__(self):
        return self.hash


class Imagem(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)  # will be 'quipo' if no one is logged.
    Picture = models.ImageField(upload_to='media/', null=True, blank=True)  # the generated hash
    senha = models.CharField(max_length=250)  # a description to facilitate remembering which file is it about.

    class Meta:
        verbose_name = 'Imagem'
        verbose_name_plural = 'Imagens'

hashes/views.py
from django.shortcuts import render
from django.urls import reverse
from hashlib import sha256
from django.contrib.auth.models import User
from .models import Hash

import json
import stripe
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from datetime import date, datetime
from django.views import View

from .tesseract_ocr import TesseractOCR

#from scripts.sendTransaction import send_hash

from asgiref.sync import async_to_sync

import asyncio

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessView(TemplateView):
    template_name = "hashes/success.html"

class CancelView(TemplateView):
    template_name = "hashes/query.html"

class CreateCheckoutSessionView(View):
    def post(self, request, *args, **kwargs):
        hash_id = self.kwargs["pk"]
        hash = Hash.objects.get(id=hash_id)
        YOUR_DOMAIN = "https://hash.quipo.io/" #http://127.0.0.1:8000
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[
                {
                    'price_data': {
                        'currency': 'brl',
                        'unit_amount': hash.price,
                        'product_data': {
                            'name': hash.description,
                            # 'images': ['https://i.imgur.com/EHyR2nP.png'],
                        },
                    },
                    'quantity': 1,
                },
            ],
            metadata={
                "product_id": hash.id
            },
            mode='payment',
            success_url = f"{YOUR_DOMAIN}/query_result/"+hash.hash,
            cancel_url= f"{YOUR_DOMAIN}",
        )
        return JsonResponse({
            'id': checkout_session.id
        })


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']

        customer_email = session["customer_details"]["email"]
        hash_id = session["metadata"]["product_id"]

        hash = Hash.objects.get(id=hash_id)

        today = datetime.today()
        hash.payment_at = today
        hash.save()

        # SEND HASH TO POLYGON
        #loop = asyncio.new_event_loop()
        #asyncio.set_event_loop(loop)
        #try:
            # Sua lógica síncrona aqui
        #    blockchain_address = async_to_sync(send_hash)(hash.hash)
        #    hash.transaction_hash = blockchain_address
        #    hash.save()
        #finally:
        #    loop.close()

        #send_mail(
        #    subject="Here is your product",
        #    message=f"Thanks for your purchase. Here is the product you ordered. The URL is {hash.url}",
        #    recipient_list=[customer_email],
        #    from_email="andre_demori@hotmail.com"
        #)

        # TODO - decide whether you want to send the file or the URL

    elif event["type"] == "payment_intent.succeeded":
        intent = event['data']['object']

        stripe_customer_id = intent["customer"]
        stripe_customer = stripe.Customer.retrieve(stripe_customer_id)

        customer_email = stripe_customer['email']
        product_id = intent["metadata"]["product_id"]

        product = Hash.objects.get(id=product_id)

        #send_mail(
        #    subject="Here is your product",
        #    message=f"Thanks for your purchase. Here is the product you ordered. The URL is ",
        #    recipient_list=[customer_email],
        #    from_email="matt@test.com"
        #)

    return HttpResponse(status=200)

class StripeIntentView(View):
    def post(self, request, *args, **kwargs):
        try:
            req_json = json.loads(request.body)
            customer = stripe.Customer.create(email=req_json['email'])
            hash_id = self.kwargs["pk"]
            hash = Hash.objects.get(id=hash_id)
            intent = stripe.PaymentIntent.create(
                amount=hash.price,
                currency='usd',
                customer=customer['id'],
                metadata={
                    "hash_id": hash.id
                }
            )
            return JsonResponse({
                'clientSecret': intent['client_secret']
            })
        except Exception as e:
            return JsonResponse({ 'error': str(e) })

def get_hash(file):
    """ This function aims to generate a hash (sha256) code for the given file. The file is read in blocks. """

    sha256_hash = sha256()
    # with open(file_name, "rb") as f:
    # Read and update hash string value in blocks of 4K
    for byte_block in iter(lambda: file.read(4096), b""):
        sha256_hash.update(byte_block)
    hash_code = sha256_hash.hexdigest()

    return hash_code


def visualizar(request, hash):
    """View that renders the upload page"""

    aprovado = False

    hash_obj = Hash.objects.get(hash=hash)

    if request.method == 'POST':
        senha = request.POST['senha']

        if hash_obj.description == senha:
            aprovado = True
        else:
            aprovado = False


    context = {
        'hash': hash_obj,
        'aprovado': aprovado
    }
    rendered_page = render(request, 'hashes/senha.html', context)
    return rendered_page

def upload(request):
    """View that renders the upload page"""

    data = {
        'target': reverse('hash'),
        'query_url': reverse('query')
    }
    rendered_page = render(request, 'hashes/upload.html', data)
    return rendered_page


def check_hash_on_db(hash_code):
    # Checking whether this hash is recorded on DB already
    result = Hash.objects.filter(hash=hash_code)
    if result:
        data = {
            'hash_id': result[0].id,
            'hash': result[0].hash,
            'description': result[0].description,
            'price': result[0].price,
            'formatted_price': "R${:,.2f}".format(result[0].price / 100),
            "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY,
            "item": result[0]
        }

        if result[0].bchain_link:
            data['e_certificate_url'] = reverse('e_certificate', args=[result[0].id])
            data['bchain_link'] = result[0].bchain_link
        if result[0].payment_at:
            data['payment_at'] = result[0].payment_at
        if result[0].transaction_at:
            data['transaction_at'] = result[0].transaction_at
        return data

    return None


def generate_hash(request):
    """View that is called when the upload is done and the user submits the file to generate hash.
    Then, this view gets the hash, records initial info on the DB and renders the page that exhibits
    the resulting hash and presents a link for payment"""

    if len(request.FILES) == 0:
        return HttpResponse('<h1>File is missing.</h1>')

    # Generating hash based on the provided file
    gen_hash = get_hash(request.FILES['uploaded_file'])
    picture = request.FILES['uploaded_file']

    data = check_hash_on_db(gen_hash)
    if data:
        rendered_page = render(request, 'hashes/existing_hash.html', data)
        return rendered_page

    # Defining which user will be used to record a new tuple on DB.
    # If there is some user logged in, then use it. Otherwise, utilize user 'quipo'.
    user = request.user
    if not user.id:
        user = User.objects.get(username="quipo")  # getting user object (quipo)
        if not user:
            return HttpResponse('<h1>User quipo is missing.</h1>')

    if not request.POST['file_description']:
        return HttpResponse('<h1>Description is missing.</h1>')

    description = request.POST['file_description']

    sigilo = int(request.POST['sigilo'])

    # Creating a new tuple on table Hash
    hash = Hash.objects.create(user=user,hash=gen_hash,description=description,price=sigilo, Picture=picture)

    new_tuple = {
        'hash_id': hash.id,
        'hash': hash.hash,
        'description': hash.description,
        'price': hash.price,
        'formatted_price': "R${:,.2f}".format(hash.price / 100),
        "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY,
        'item': hash
    }

    rendered_page = render(request, 'hashes/hash.html', new_tuple)
    return rendered_page

def query(request):
    """View that renders the page to make queries (by hash and by the file itself)"""
    data = {
        'target': reverse('query_result'),
        "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
    }

    #hash = Hash.objects.last()
    #if hash:
        # Ensure send_hash is properly defined as an async function elsewhere
    #    blockchain_address = async_to_sync(send_hash)(hash.hash)
    #    hash.transaction_hash = blockchain_address
    #    hash.save()

    rendered_page = render(request, 'hashes/query.html', data)
    return rendered_page


def query_result(request, hash_code=None):
    """View that renders the page with the query result"""

    if hash_code:
        gen_hash = hash_code
    elif len(request.FILES) > 0:
        # Generating hash based on the provided file
        gen_hash = get_hash(request.FILES['uploaded_file'])
    elif request.POST['hash']:
        gen_hash = request.POST['hash']
    else:
        return HttpResponse('<h1>Neither a file nor a hash was provided.</h1>')

    data = check_hash_on_db(gen_hash)

    # Notice that data may be null if the hash code is not on DB.

hashes/templates/hashes/cancel.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block body %}

<div  style="text-align:center"><br><br>
    <p>
      <b>Pagamento cancelado.</b> <br><br>

  <div class="container" style="z-index: 0;">
    <div class="center button__rdoc">
        <a href="{% url 'query' %}" class="w3-button w3-round-xxlarge w3-large w3-padding-large button__doc" style="width: 80%; background-color: #001F5F; color: #fff">{% trans "Voltar"%}</a>
    </div>
  </div>

{% endblock body %}

hashes/templates/hashes/existing_hash.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block body %}

<div  style="text-align:center">
    <p><br><br>
      O hash do arquivo fornecido já encontra-se em nossos sistemas. <br><br>

        {% if payment_at %}
        {{hash}}

            <img src="{{ Picture.url }}" alt="Avatar" class="profile_picture" align="center" style="width: 200px; height: 200px;">

    </p>
    <p>
      <b>Descrição do arquivo:</b> <br>{{description}}
    </p>
      {% if bchain_link %}
        <p>
          Link para o registro em blockchain: <a href="{{bchain_link}}" target="_blank">aqui</a>
        </p>
        <p>

          <!--<a href="{{e_certificate_url}}" target="_blank">Visualizar e-certificado</a>-->
        </p>
        <br><br>
        <a href="{% url 'query' %}" class="w3-button w3-round-xxlarge w3-large w3-padding-large button__doc" style="width: 80%; background-color: #001F5F; color: #fff">{% trans "Voltar"%}</a><br><br>
      {% else %}
        <p>
        </p>

        <br><br>

    <a href="javascript:history.back()" >Voltar</a><br><br>
      {% endif %}
    {% else %}

      <div class="product">
        {% comment %} <img
          src="https://i.imgur.com/EHyR2nP.png"
          alt="The cover of Stubborn Attachments"
        /> {% endcomment %}
        <div class="description">{{hash}}<br><br>


        <img src="{{ item.Picture_noise.url }}" alt="Avatar"  align="center" style="width: 500px; height: 500px;"><br>

          <a href="{% url 'visualizar' hash=hash %}" class="w3-button w3-round-xxlarge w3-large w3-padding-large button__doc" style="width: 40%; background-color: #001F5F; color: white; display: inline-block; text-align: center; line-height: normal;">{% trans 'Visualizar arquivo' %}</a>

        </div>
      </div>

    <br><br>

    <div class="container" style="z-index: 0;">
        <div class="center button__rdoc">
            <a href="{% url 'query' %}" class="w3-button w3-round-xxlarge w3-large w3-padding-large button__doc" style="width: 80%; background-color: #001F5F; color: #fff">{% trans "Voltar"%}</a>
        </div>
      </div>
</div>
    {% endif %}

    {% csrf_token %}

<script type="text/javascript">
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
      fetch("{% url 'hashes:create-checkout-session' hash_id %}", {
        method: "POST",
        headers: {
            'X-CSRFToken': csrftoken
        }
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });

    // Disable the button until we have Stripe set up on the page
    //document.querySelector("button").disabled = true;

    var elements = stripe.elements();
    var style = {
      base: {
        color: "#32325d",
        fontFamily: 'Arial, sans-serif',
        fontSmoothing: "antialiased",
        fontSize: "16px",
        "::placeholder": {
          color: "#32325d"
        }
      },
      invalid: {
        fontFamily: 'Arial, sans-serif',
        color: "#fa755a",
        iconColor: "#fa755a"
      }
    };
    var card = elements.create("card", { style: style });
    // Stripe injects an iframe into the DOM
    card.mount("#card-element");
    card.on("change", function (event) {
      // Disable the Pay button if there are no card details in the Element
      document.querySelector("button").disabled = event.empty;
      document.querySelector("#card-error").textContent = event.error ? event.error.message : "";
    });
    var form = document.getElementById("payment-form");
    form.addEventListener("submit", function(event) {
      event.preventDefault();
      // Complete payment when the submit button is clicked
      fetch("/hashes/create-payment-intent/" + hash_id + "/", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          'X-CSRFToken': csrftoken
        },
        body: JSON.stringify({
          email: document.getElementById('email').value
        })
      })
        .then(function(result) {
          return result.json();
        })
        .then(function(data) {
          payWithCard(stripe, card, data.clientSecret);
        });
    });

    // Calls stripe.confirmCardPayment
    // If the card requires authentication Stripe shows a pop-up modal to
    // prompt the user to enter authentication details without leaving your page.
    var payWithCard = function(stripe, card, clientSecret) {
      loading(true);
      stripe
        .confirmCardPayment(clientSecret, {
          payment_method: {
            card: card
          }
        })
        .then(function(result) {
          if (result.error) {
            // Show error to your customer
            showError(result.error.message);
          } else {
            // The payment succeeded!
            orderComplete(result.paymentIntent.id);
          }
        });
    };
    /* ------- UI helpers ------- */
    // Shows a success message when the payment is complete
    var orderComplete = function(paymentIntentId) {
      loading(false);
      document
        .querySelector(".result-message a")
        .setAttribute(
          "href",
          "https://dashboard.stripe.com/test/payments/" + paymentIntentId
        );
      document.querySelector(".result-message").classList.remove("hidden");
      document.querySelector("button").disabled = true;
    };
    // Show the customer the error from Stripe if their card fails to charge
    var showError = function(errorMsgText) {
      loading(false);
      var errorMsg = document.querySelector("#card-error");
      errorMsg.textContent = errorMsgText;
      setTimeout(function() {
        errorMsg.textContent = "";
      }, 4000);
    };
    // Show a spinner on payment submission
    var loading = function(isLoading) {
      if (isLoading) {
        // Disable the button and show a spinner
        document.querySelector("button").disabled = true;
        document.querySelector("#spinner").classList.remove("hidden");
        document.querySelector("#button-text").classList.add("hidden");
      } else {
        document.querySelector("button").disabled = false;
        document.querySelector("#spinner").classList.add("hidden");
        document.querySelector("#button-text").classList.remove("hidden");
      }
    };

  </script>

{% endblock body %}

hashes/templates/hashes/footer.html
{% load static %}
<footer id="footer_desktop">
    <div class="w3-bar container" style="height: 160px; ">
        <div class="vertical-center center">

          <div class="first_div">
            <img class="local_img" src="{% static 'img/local.webp' %}">
            <a href="https://www.lncc.br/"><p class="local_text">LNCC - Av. Getulio Vargas, 333 - Quitandinha, Petrópolis - RJ</p></a>
          </div>

          <div class="middle_div">
            <div class="center">
              <img class="white_quipo" src="{% static 'img/logo-branca.webp' %}">
            </div>

            <div class="center">
              <p class="social">
                <img class="linkedin" src="{% static 'img/linkedin.webp' %}">
                <img class="instagram" src="{% static 'img/instagram.webp' %}">
              </p>
              <p class="apps">
                <img class="appstore" src="{% static 'img/app-store.webp' %}">
                <img class="playstore" src="{% static 'img/play-store.webp' %}">
              </p>
            </div>
          </div>

          <div class="last_div">
            <img class="email" src="{% static 'img/email.png' %}">
            <a href="mailto:quipo@quipo.io"> <p class="email_text">quipo@quipo.io</p> </a>
          </div>
        </div>
    </div>
</footer>

<footer id="footer_mobile" style="display:none;">
    <div style="text-align: center; padding: 10px 0;"><img class="white_quipo" src="{% static 'img/logo-branca.webp' %}"></div>

    <div style="color: white; text-align: center; padding: 10px 0;">
         <img class="local_img" src="{% static 'img/local.webp' %}">
            <a href="https://www.lncc.br/"><p class="local_text">LNCC - Av. Getulio Vargas, 333 - Quitandinha, Petrópolis - RJ</p></a>
    </div>

    <div style="color: white; text-align: center; padding: 10px 0;">
        <img class="email" src="{% static 'img/email.png' %}">
        <a href="mailto:quipo@quipo.io" style="text-decoration: none;"> <p class="email_text">quipo@quipo.io</p> </a>
    </div>

    <div style="text-align: center; padding: 10px 0;">

        <img class="linkedin" src="{% static 'img/linkedin.webp' %}">
        <img class="instagram" src="{% static 'img/instagram.webp' %}">

        <img class="appstore" src="{% static 'img/app-store.webp' %}">
        <img class="playstore" src="{% static 'img/play-store.webp' %}">

    </div>


</footer>

hashes/templates/hashes/hash.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block body %}

<div  style="text-align:center"><br><br>
    <p>
      <b>O Hash do arquivo foi gerado em nosso sistema.</b> <br><br>
            {{hash}}<br><br>


    <div class="product">
        {% comment %} <img
          src="https://i.imgur.com/EHyR2nP.png"
          alt="The cover of Stubborn Attachments"
        /> {% endcomment %}
      </div>
    </div><br>

  <div class="container" style="z-index: 0;">
    <div class="center button__rdoc">
        <a href="{% url 'query' %}" class="w3-button w3-round-xxlarge w3-large w3-padding-large button__doc" style="width: 80%; background-color: #001F5F; color: #fff">{% trans "Consultar Hash"%}</a>    </div>
    </div>

    {% csrf_token %}

<script type="text/javascript">
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
      fetch("{% url 'hashes:create-checkout-session' hash_id %}", {
        method: "POST",
        headers: {
            'X-CSRFToken': csrftoken
        }
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });

    // Disable the button until we have Stripe set up on the page
    //document.querySelector("button").disabled = true;

    var elements = stripe.elements();
    var style = {
      base: {
        color: "#32325d",
        fontFamily: 'Arial, sans-serif',
        fontSmoothing: "antialiased",
        fontSize: "16px",
        "::placeholder": {
          color: "#32325d"
        }
      },
      invalid: {
        fontFamily: 'Arial, sans-serif',
        color: "#fa755a",
        iconColor: "#fa755a"
      }
    };
    var card = elements.create("card", { style: style });
    // Stripe injects an iframe into the DOM
    card.mount("#card-element");
    card.on("change", function (event) {
      // Disable the Pay button if there are no card details in the Element
      document.querySelector("button").disabled = event.empty;
      document.querySelector("#card-error").textContent = event.error ? event.error.message : "";
    });
    var form = document.getElementById("payment-form");
    form.addEventListener("submit", function(event) {
      event.preventDefault();
      // Complete payment when the submit button is clicked
      fetch("/hashes/create-payment-intent/" + hash_id + "/", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          'X-CSRFToken': csrftoken
        },
        body: JSON.stringify({
          email: document.getElementById('email').value
        })
      })
        .then(function(result) {
          return result.json();
        })
        .then(function(data) {
          payWithCard(stripe, card, data.clientSecret);
        });
    });

    // Calls stripe.confirmCardPayment
    // If the card requires authentication Stripe shows a pop-up modal to
    // prompt the user to enter authentication details without leaving your page.
    var payWithCard = function(stripe, card, clientSecret) {
      loading(true);
      stripe
        .confirmCardPayment(clientSecret, {
          payment_method: {
            card: card
          }
        })
        .then(function(result) {
          if (result.error) {
            // Show error to your customer
            showError(result.error.message);
          } else {
            // The payment succeeded!
            orderComplete(result.paymentIntent.id);
          }
        });
    };
    /* ------- UI helpers ------- */
    // Shows a success message when the payment is complete
    var orderComplete = function(paymentIntentId) {
      loading(false);
      document
        .querySelector(".result-message a")
        .setAttribute(
          "href",
          "https://dashboard.stripe.com/test/payments/" + paymentIntentId
        );
      document.querySelector(".result-message").classList.remove("hidden");
      document.querySelector("button").disabled = true;
    };
    // Show the customer the error from Stripe if their card fails to charge
    var showError = function(errorMsgText) {
      loading(false);
      var errorMsg = document.querySelector("#card-error");
      errorMsg.textContent = errorMsgText;
      setTimeout(function() {
        errorMsg.textContent = "";
      }, 4000);
    };
    // Show a spinner on payment submission
    var loading = function(isLoading) {
      if (isLoading) {
        // Disable the button and show a spinner
        document.querySelector("button").disabled = true;
        document.querySelector("#spinner").classList.remove("hidden");
        document.querySelector("#button-text").classList.add("hidden");
      } else {
        document.querySelector("button").disabled = false;
        document.querySelector("#spinner").classList.add("hidden");
        document.querySelector("#button-text").classList.remove("hidden");
      }
    };

  </script>

{% endblock body %}

hashes/templates/hashes/success.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block body %}

<div  style="text-align:center"><br><br>
    <p>
      <b>Pagamento efetuado com sucesso.</b> <br><br>
      {% if payment_at %}
            {{hash}}
        </p>
        <p>
          <b>Descrição:</b> <br><br>{{description}}
        </p>
      {% endif %}

  <div class="container" style="z-index: 0;">
    <div class="center button__rdoc">
        <a href="{% url 'query' %}" class="w3-button w3-round-xxlarge w3-large w3-padding-large button__doc" style="width: 80%; background-color: #001F5F; color: #fff">{% trans "Voltar"%}</a>
    </div>
  </div>

{% endblock body %}